name: myworkflow

on: push

jobs:
  action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: check code
        uses : actions/checkout@v4
      - name: print code 
        run: cat index.html
