name: inputs demo

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  inputs-demo:
    runs-on: ubuntu-latest
    steps:
      - name: deploy the app
        run: echo "deploy app to ${{ github.event.inputs.environment }}"
