name: inputs demo

on: 
  push:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: build
        run: echo "build"

  test:
    needs: build   # 👈 test waits until build finishes successfully
    runs-on: ubuntu-latest
    steps: 
      - name: test
        run: echo "test"

  deploy:
    needs: test    # 👈 deploy waits until test finishes successfully
    runs-on: ubuntu-latest
    steps: 
      - name: deploy
        run: echo "deploy"


