on:
  workflow_dispatch:
    inputs:
      env:
        description: "Choose environment"
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ github.event.inputs.env }}"
