name: outputs demo
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - id: version
        run: echo "version=3.5.2" >> $GITHUB_OUTPUT

      # Same job usage
      - run: echo "Same job: ${{ steps.version.outputs.version }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Other job usage
      - run: echo "Other job: ${{ needs.build.outputs.version }}"

